# Site settings
title: Isaac Hawkins # site title
description: Full-stack developer with experience building data-intensive SaaS products. React, PHP, Node.js, PostgreSQL, and Linux.
lang: en-US # default lang
timezone: Melbourne/Australia # set your timezone
image: assets/img/avatar.png # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Isaac Hawkins # author name
  bio: Full-Stack Developer
  username: Jellyfish # general username
  github: Jelly-Fish-Dev # github username
  linkedin: isaac-g-hawkins # linkedin username
  #twitter: twitter_username # twitter username
  #facebook: facebook_username # facebook username
  email: isaac@isaachawkins.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: "https://www.isaachawkins.com" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  projects:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
